name: Daily Commit

on:
  schedule:
    - cron: "0 3 * * *"  # Runs daily at 03:00 UTC (Modify as needed)

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Status File (22f2000770@ds.study.iitm.ac.in)
        run: |
          echo "Last updated: $(date)" > status.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "22f2000770@ds.study.iitm.ac.in"
          git add status.txt
          git commit -m "Automated daily commit"
          git push
