name: Daily Commit

on:
  schedule:
    - cron: '30 4 * * *' # Runs daily at 4:30 AM UTC. Adjust as needed.

jobs:
  daily_update:
    runs-on: ubuntu-latest
    steps:
      - name: Your Email (22f2000770@ds.study.iitm.ac.in)
        run: echo "Daily update triggered"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make a change
        run: |
          echo "Last updated: $(date)" > updated.txt  # Add timestamp to updated.txt

      - name: Commit changes
        uses: stefanzweifel/git-cli-action@v2
        with:
          actions: commit
          repository: .
          args: -m "Automated daily update" -a # Commit all changes

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} # Push to the current branch
